test: replace lazyNew() with newInstance()
Because tests fail
1) Aura\Cli_Kernel\CliKernelTest::testHelpCommand
TypeError: Argument 1 passed to Aura\Cli_Kernel\HelpCommand::__construct() must be an instance of Aura\Cli\Stdio, string given